[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.20"
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config